### ISSUE TITLE
无法正确处理QUIC/H2嵌套

### ISSUE THREAD

**Issue by Dounutsubtly** [Itsusinn/tuic#10]
其一为Firefox无法连接支持h2的websockets,并且由于其降级机制问题,导致完全无法连接
about:config中关闭network.http.http2.websockets后正常

其二为支持QUIC的网站均被自动降级

**Comment by Itsusinn** [comment]
firefox是如何代理的？手动添加的socks代理服务器吗？用的啥客户端，我看看能不能复现

**Comment by Dounutsubtly** [comment]
直接读取的系统代理

**Comment by Dounutsubtly** [comment]
Chromium系碰上h2 ws连不上会自动降级h1.1，但是firefox当h2第一个包成功后，无法进行降级

**Comment by Dounutsubtly** [comment]
临时解决方案为和hy2一样屏蔽443端口的UDP包

**Comment by Dounutsubtly** [comment]
![1](https://github.com/user-attachments/assets/6f82ce8a-7276-4df1-83a8-d50a7ceee186)
![1](https://github.com/user-attachments/assets/0c2f9afc-9d79-428d-acd8-18dfaedff1c3)

**Comment by Dounutsubtly** [comment]
根据之前的日志，http2，也是走的这个地方，h2代理需要再判断一次

**Comment by Dounutsubtly** [comment]
目前的情况是Firefox 走代理时 HTTP2 和 HTTP3/QUIC 都有问题

**Comment by Dounutsubtly** [comment]
晚点再研究，先Close了

**Comment by Dounutsubtly** [comment]
找到原因了，调了一天给我整麻了

**Comment by Itsusinn** [comment]
我试了试，129ff+1.0.3tuic-server是可以通的

**Comment by Itsusinn** [comment]
> 我试了试，129ff+1.0.3tuic-server是可以通的

从ff开发者工具里看到握手使用的是http/1.1

**Comment by Dounutsubtly** [comment]
about:config中network.http.http2.websockets是开启的吗
另外我的客户端一直是nekoray，也就是singbox内核

**Comment by Dounutsubtly** [comment]
内核方面应该是和 @Fhokud 一样的，之前因为client一直被defender报毒就用的nekoray，会出现ff连接ws会失败的问题

**Comment by Itsusinn** [comment]
network.http.http2.websockets是true

此外在ff131上确实出现了连接失败，但在重试两次后就好了，很是奇怪。tuic server报的错误的reset by peer

**Comment by Itsusinn** [comment]
关于http3,系统代理可能不能正确代理udp流量
我使用了clashmeta的tun,且关闭firefox的socks5代理，测试了网站 https://cloudflare-quic.com/
为http3连接
