### ISSUE TITLE
Online Users

### ISSUE THREAD

**Issue by HamedAp** [Itsusinn/tuic#15]
Hello 
Is there any way to view online users ? 
any command to show online users ?

**Comment by Itsusinn** [comment]
Not supported right now.
Low priority & welcome pull request.

**Comment by Itsusinn** [comment]
> Would you please tell me where is log file ? 
> location of log file i mean . 

Tuic-server only prints log to the terminal.

**Comment by HamedAp** [comment]
So can we split it and have tuic.log just for it ? 
maybe change in json file :
  "log_level": "warn"

**Comment by HamedAp** [comment]
it will be great if you added . 
we can parse it and get online users :)

**Comment by Itsusinn** [comment]
Oh, you just need online users.
Let me implement it then.

**Comment by HamedAp** [comment]
I found out some log for login and logout :

Login :
`Sep 10 11:32:07 Srver tuic-server[1552929]: [2024-09-10T08:02:07Z INFO ] [0x2b9201c0] [[::ffff:***MYIP***]:51639] [752da45f-4f5e-49e3-9047-816d53e7363b] [authenticate] 752da45f-4f5e-49e3-9047-816d53e7363b`


Logout : 
`Sep 10 11:35:07 Srver  tuic-server[1552929]: [2024-09-10T08:05:07Z WARN ] [0x2b91c2e0] [[::ffff:***MYIP***]:34074] [752da45f-4f5e-49e3-9047-816d53e7363b] connection error: closed by peer: 0`

Maybe It Helps :)
