### ISSUE TITLE
windows 版本有问题

### ISSUE THREAD

**Issue by 328902301** [Itsusinn/tuic#37]
最近几个 tuic-client-x86_64-windows.exe  都无法使用

**Comment by Itsusinn** [comment]
可能是因为x86_64的cpu指令集设置的高了。
你用tuic-client-i686-windows.exe试试

**Comment by 328902301** [comment]
这个是可以的

**Comment by Itsusinn** [comment]
tuic-client-x86_64-windows.exe 有错误日志吗？

**Comment by 328902301** [comment]
thread 'main' panicked at C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.23.20\src\crypto\mod.rs:249:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Itsusinn** [comment]
不是指令集引起的，确实有bug

**Comment by Itsusinn** [comment]
我没法在自己的机器上复现这个bug,你尝试一下 https://github.com/Itsusinn/tuic/releases/tag/v1.3.6 的tuic-client-x86_64-windows.exe

**Comment by 328902301** [comment]
v1.3.6 和 latest 这两个版本的 tuic-client-x86_64-windows.exe 都测试没问题。

**Comment by Itsusinn** [comment]
好
