### ISSUE TITLE
shadowrocket不能连接

### ISSUE THREAD

**Issue by catding** [Itsusinn/tuic#38]
大佬，才发现你的项目
刚尝试了下，在android上使用MiProxy客户端连接没有问题，但是Shadowrocket连接一直失败，debug提示：
24-12-19 08:16:36 DEBUG tuic_server::server: [Incoming] Failed to accept connection: the cryptographic handshake failed: error 120: peer doesn't support any known protocol
麻烦大佬帮指导下

**Comment by Itsusinn** [comment]
客户端和服务端的alpn必须要一致.
服务端默认是h3

**Comment by catding** [comment]
太棒了，alpn设置后app可以正常使用。
另外大佬能否增加个adduuid的api呢，这样功能就完整了

**Comment by catding** [comment]
另外，刚刚在中国移动网络下玩了会儿，一会儿速度就上不去了，android上用电信和联通的，速度还稳定。

**Comment by Itsusinn** [comment]
> 太棒了，alpn设置后app可以正常使用。 另外大佬能否增加个adduuid的api呢，这样功能就完整了

在restful api里吗？不太行（从逻辑架构上来讲）。推荐预先在配置文件里分配大量uuid
