### ISSUE TITLE
handling incoming bidirectional stream error: error unmarshalling bi_stream: unexpected end of file

### ISSUE THREAD

**Issue by Dounutsubtly** [Itsusinn/tuic#7]
https://websocketking.com/
任何长连接持续几秒后自动断开，原作者仓库版本可复现

**Comment by Dounutsubtly** [comment]
日志：
https://gist.github.com/Dounutsubtly/236f18bcd0db00e2ebbbaf32ca96b4dd

**Comment by Dounutsubtly** [comment]
这个问题目前只在Firefox上出现，Edge正常，应该是某种安全机制

**Comment by Dounutsubtly** [comment]
应该是火狐的问题

**Comment by Itsusinn** [comment]
end of life不是异常，这个一般是对端没有正常执行(或实现)关闭操作造成的
