### ISSUE TITLE
【构想】使用 LuaJIT 做一个服务端的规则引擎

### ISSUE THREAD

**Issue by Dounutsubtly** [Itsusinn/tuic#9]
碎碎念：
客户端的规则引擎非常多，再做就是重复造轮子，但是服务端的还是有必要的，参考openresty，可以设计一个使用LuaJIT的规则引擎，独立于配置文件，以插件形式加载。

看看就好，只是一个想法，实现起来会很折磨。

**Comment by Itsusinn** [comment]
我的想法是找一个（或做一个）rust界的sing-box，咱只负责协议相关的东西

**Comment by Dounutsubtly** [comment]
> 我的想法是找一个（或做一个）rust界的sing-box，咱只负责协议相关的东西

目前是服务端的出口固定，只能走默认路由表，主要需求就是特定网站走特定的出口，绕回来又是重复造轮子
